site_name: INBCM
site_description: Documentação do INBCM
site_author: Douglas de Araújo

nav:
  - Inicio: 'index.md'
  - 'Primeiros Passos':
    - 'Configurando o ambiente': 'guias/ambiente.md'
    - 'Instalando o Wordpress': 'guias/wordpress.md'
  - Arquitetura:
    - 'INBCM': 'arquitetura/requisitos/inbcm.md'
    - 'Tainacam Sync': 'arquitetura/requisitos/tainacam-sync.md'
    - 'Cliente Offline': 'arquitetura/requisitos/cliente-offline.md'
  - Padrões: 
      - 'Arquivos de invetário': 'arquitetura/padroes/arquivos.md'
      - 'Imagens': 'arquitetura/padroes/imagens.md'
  - Processos:
      - 'Validação de invetário': 'arquitetura/processos/validacao.md'
      - 'Manutenção de imagens': 'arquitetura/processos/manutencao-imagens.md'
  - Segurança:
    - 'Observações': 'arquitetura/seguranca/seguranca.md'
theme: readthedocs
plugins:
  - search
  - mermaid2